#!/usr/bin/env python3
"""Writes the test coverage inventory (docs/coverage.md) from the JaCoCo XML reports of both projects.

Run after `mvn verify` of both projects (make build, make test or make scan). For each project it gives line and
branch coverage against the 100% target and lists every class below the target: for the shortener with the
documented reason from policies/policies.yaml (the test-coverage gate enforces those), for the orchestrator as a
gap inventory ordered by missed lines. Standard library only.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECTS = [
    ("Shortener (the product the QA agent covers)", ROOT / "shortener-service/target/site/jacoco/jacoco.xml",
     "98.5% line, 100% branch"),
    ("Orchestrator", ROOT / "orchestrator/target/site/jacoco/jacoco.xml", "88% line, 75% branch"),
]


def counter(element, kind):
    for item in element.findall("counter"):
        if item.get("type") == kind:
            return int(item.get("missed")), int(item.get("covered"))
    return 0, 0


def percent(missed, covered):
    total = missed + covered
    return 100.0 if total == 0 else 100.0 * covered / total


def exceptions():
    text = (ROOT / "policies/policies.yaml").read_text()
    block = re.search(r"^  exceptions:\n((?:    .+\n)+)", text, re.MULTILINE)
    if not block:
        return {}
    return {name: reason for name, reason in re.findall(r'^    ([\w.$]+): "(.*)"$', block.group(1), re.MULTILINE)}


def below_target(report):
    classes = []
    for package in report.findall("package"):
        for cls in package.findall("class"):
            line = counter(cls, "LINE")
            branch = counter(cls, "BRANCH")
            if line[0] or branch[0]:
                classes.append((cls.get("name").replace("/", "."), line, branch))
    return sorted(classes, key=lambda item: (-item[1][0], item[0]))


def main():
    reasons = exceptions()
    out = ["# Test coverage", "",
           "Generated by `scripts/coverage-report.py` from the JaCoCo reports; do not edit by hand. The target is 100% "
           "line and branch coverage. Every class below it is listed here. The build fails below the floor, and the "
           "`test-coverage` gate fails for any shortener class below target that is not a documented exception.", "",
           "| Project | Line | Branch | Floor enforced by `mvn verify` | Classes below 100% |", "|---|---:|---:|---|---:|"]
    sections = []
    for title, path, floor in PROJECTS:
        if not path.exists():
            sys.exit(f"missing {path.relative_to(ROOT)}: run mvn verify for both projects first")
        report = ET.parse(path).getroot()
        line, branch = counter(report, "LINE"), counter(report, "BRANCH")
        gaps = below_target(report)
        out.append(f"| {title} | {percent(*line):.1f}% ({line[1]}/{sum(line)}) | {percent(*branch):.1f}% "
                   f"({branch[1]}/{sum(branch)}) | {floor} | {len(gaps)} |")
        rows = [f"## {title}", ""]
        if not gaps:
            rows.append("Every class is at 100% line and branch coverage.")
        else:
            rows += ["| Class | Missed lines | Line | Branch | Why the target is not met |", "|---|---:|---:|---:|---|"]
            for name, (line_missed, line_covered), (branch_missed, branch_covered) in gaps:
                reason = reasons.get(name.split("$")[0], "open gap: not yet covered by a test")
                rows.append(f"| `{name}` | {line_missed} | {percent(line_missed, line_covered):.1f}% | "
                            f"{percent(branch_missed, branch_covered):.1f}% | {reason} |")
        sections += rows + [""]
    print("\n".join(out + [""] + sections).rstrip() + "\n", end="")


if __name__ == "__main__":
    main()
