CREATE TABLE link (
    code       VARCHAR(32)   NOT NULL PRIMARY KEY,
    url        VARCHAR(2048) NOT NULL,
    url_hash   CHAR(64)      NOT NULL,
    created_at TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX ux_link_url_hash ON link (url_hash);

CREATE TABLE click (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(32) NOT NULL,
    clicked_at TIMESTAMP   NOT NULL,
    CONSTRAINT fk_click_link FOREIGN KEY (code) REFERENCES link (code)
);

CREATE INDEX ix_click_code_clicked_at ON click (code, clicked_at);
